import * as THREE from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';import {PAXLoader,configureDecoders,createGLTFLoader} from '../src/index.js';
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));document.body.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#263138');scene.environment=new THREE.PMREMGenerator(renderer).fromScene(new RoomEnvironment(),.04).texture;
const camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.001,1000);camera.position.set(0,0,5);const controls=new OrbitControls(camera,renderer.domElement);
const $=id=>document.getElementById(id),loader=new PAXLoader();loader.gltfLoader=configureDecoders(createGLTFLoader(),renderer);let session,gltf,start=0,first=null;
const lock=busy=>{for(const id of ['base','tile','full'])$(id).disabled=busy||id!=='base'&&!session;};
const status=()=>{$('status').textContent=`${(session.bytes/1024).toFixed(1)} KiB downloaded · first scene ${first.toFixed(2)} s · ${session.complete?'Full detail':'Partial detail'}`;};
$('base').onclick=async()=>{lock(true);session?.dispose();if(gltf)scene.remove(gltf.scene);session=null;start=performance.now();try{session=await loader.load(`/stream/${$('asset').value}.pax?kbps=2048&latency=80`,{transport:'range',maxLevel:0,onProgress:e=>{$('status').textContent=`${(e.bytes/1024).toFixed(1)} KiB downloaded…`;},onScene(asset){gltf=asset;scene.add(gltf.scene);const box=new THREE.Box3().setFromObject(gltf.scene),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(0,size*.25,size*1.4));camera.far=Math.max(100,size*10);camera.updateProjectionMatrix();controls.update();first=(performance.now()-start)/1000;}});status();}catch(e){$('status').textContent=e.message;}finally{lock(false);}};
async function refine(options){lock(true);try{session=await session.refine(options);status();}catch(e){$('status').textContent=e.message;}finally{lock(false);}}
$('tile').onclick=()=>refine({primitives:[],images:[0],tiles:[0]});$('full').onclick=()=>refine({});
const clock=new THREE.Clock();renderer.setAnimationLoop(()=>{gltf?.interactivity?.update(clock.getDelta());renderer.render(scene,camera);});
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
